In [ ]:
from pathlib import Path


In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
from glob import glob

In [ ]:
from sklearn.utils import shuffle

In [ ]:
import zipfile

In [ ]:
zip_path = "/content/combined_danmini.zip"

In [ ]:
extract_path = "/content/Danmini"

In [ ]:
if not Path(extract_path).exists():
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)
    print("Dataset unzipped.")
else:
    print("Dataset already unzipped.")

Dataset unzipped.


In [ ]:
df_dan = pd.read_csv(zip_path)

print("Loaded Danmini:", df_dan.shape)


Loaded Danmini: (100000, 116)


In [ ]:
#Danmini doorbell device section

In [ ]:
print(" Danmini head ")
display(df_dan.head())

print("\n Danmini columns (count {}) ".format(len(df_dan.columns)))
print(df_dan.columns.tolist())




 Danmini head 


MI_dir_L5_weight  MI_dir_L5_mean  MI_dir_L5_variance  MI_dir_L3_weight  \
0         56.956159       60.000008        1.200415e-04         74.515875   
1          3.999746      102.000000        5.460000e-12          3.999847   
2        102.247164      482.920804        3.006087e+04        179.063254   
3        152.304884      351.024155        5.907087e+04        247.726595   
4        127.088053       68.626537        4.639779e+01        205.765158   

   MI_dir_L3_mean  MI_dir_L3_variance  MI_dir_L1_weight  MI_dir_L1_mean  \
0       60.000392        5.882340e-03        209.140965       60.009242   
1      102.000000        1.820000e-12          3.999961      101.999988   
2      462.811648        3.673173e+04        597.930404      415.750605   
3      353.178703        5.887653e+04        686.987256      370.879462   
4       69.438076        4.309579e+01        640.200338       69.629745   

   MI_dir_L1_variance  MI_dir_L0.1_weight  ...  HpHp_L0.1_covariance  \
0            0.138544         2252.805690  ...          0.000000e+00   
1            0.000049            4.884512  ...         -4.300000e-48   
2        49182.272480         6340.144554  ...          0.000000e+00   
3        56928.406994         6444.376190  ...          0.000000e+00   
4           42.104223         6671.860844  ...          0.000000e+00   

   HpHp_L0.1_pcc  HpHp_L0.01_weight  HpHp_L0.01_mean  HpHp_L0.01_std  \
0            0.0           1.000000             60.0             0.0   
1            0.0           4.218989            102.0             0.0   
2            0.0           1.000000             60.0             0.0   
3            0.0           1.000000            554.0             0.0   
4            0.0           1.000000             60.0             0.0   

   HpHp_L0.01_magnitude  HpHp_L0.01_radius  HpHp_L0.01_covariance  \
0             60.000000       0.000000e+00           0.000000e+00   
1            144.249783       1.820000e-12          -9.260000e-29   
2             60.000000       0.000000e+00           0.000000e+00   
3            554.000000       0.000000e+00           0.000000e+00   
4             60.000000       0.000000e+00           0.000000e+00   

   HpHp_L0.01_pcc   label  
0             0.0   mirai  
1             0.0  benign  
2             0.0   mirai  
3             0.0   mirai  
4             0.0   mirai  

[5 rows x 116 columns]


 Danmini columns (count 116) 
['MI_dir_L5_weight', 'MI_dir_L5_mean', 'MI_dir_L5_variance', 'MI_dir_L3_weight', 'MI_dir_L3_mean', 'MI_dir_L3_variance', 'MI_dir_L1_weight', 'MI_dir_L1_mean', 'MI_dir_L1_variance', 'MI_dir_L0.1_weight', 'MI_dir_L0.1_mean', 'MI_dir_L0.1_variance', 'MI_dir_L0.01_weight', 'MI_dir_L0.01_mean', 'MI_dir_L0.01_variance', 'H_L5_weight', 'H_L5_mean', 'H_L5_variance', 'H_L3_weight', 'H_L3_mean', 'H_L3_variance', 'H_L1_weight', 'H_L1_mean', 'H_L1_variance', 'H_L0.1_weight', 'H_L0.1_mean', 'H_L0.1_variance', 'H_L0.01_weight', 'H_L0.01_mean', 'H_L0.01_variance', 'HH_L5_weight', 'HH_L5_mean', 'HH_L5_std', 'HH_L5_magnitude', 'HH_L5_radius', 'HH_L5_covariance', 'HH_L5_pcc', 'HH_L3_weight', 'HH_L3_mean', 'HH_L3_std', 'HH_L3_magnitude', 'HH_L3_radius', 'HH_L3_covariance', 'HH_L3_pcc', 'HH_L1_weight', 'HH_L1_mean', 'HH_L1_std', 'HH_L1_magnitude', 'HH_L1_radius', 'HH_L1_covariance', 'HH_L1_pcc', 'HH_L0.1_weight', 'HH_L0.1_mean', 'HH_L0.1_std', 'HH_L0.1_magnitude', 'HH_L0.1_r

In [ ]:
print(" Danmini info ")
df_dan.info()


 Danmini info 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Columns: 116 entries, MI_dir_L5_weight to label
dtypes: float64(115), object(1)
memory usage: 88.5+ MB


In [ ]:
print(" Danmini describe (numeric) ")
display(df_dan.describe().T.head(20))



 Danmini describe (numeric) 


count          mean           std   min  \
MI_dir_L5_weight       100000.0    118.156446     47.558858   1.0   
MI_dir_L5_mean         100000.0    236.967179    167.376373  60.0   
MI_dir_L5_variance     100000.0  26417.753761  25956.607916   0.0   
MI_dir_L3_weight       100000.0    187.414602     74.217395   1.0   
MI_dir_L3_mean         100000.0    237.993219    158.371070  60.0   
MI_dir_L3_variance     100000.0  29494.400327  27224.460727   0.0   
MI_dir_L1_weight       100000.0    542.053583    213.391164   1.0   
MI_dir_L1_mean         100000.0    239.691622    152.704294  60.0   
MI_dir_L1_variance     100000.0  31477.649248  28166.086519   0.0   
MI_dir_L0.1_weight     100000.0   5246.779451   2047.565171   1.0   
MI_dir_L0.1_mean       100000.0    240.652448    152.395909  60.0   
MI_dir_L0.1_variance   100000.0  31678.419764  28225.324988   0.0   
MI_dir_L0.01_weight    100000.0  34478.956777  18216.724104   1.0   
MI_dir_L0.01_mean      100000.0    240.602203    152.529036  60.0   
MI_dir_L0.01_variance  100000.0  31682.565582  28214.991060   0.0   
H_L5_weight            100000.0    118.156446     47.558858   1.0   
H_L5_mean              100000.0    236.967179    167.376373  60.0   
H_L5_variance          100000.0  26417.753761  25956.607916   0.0   
H_L3_weight            100000.0    187.414602     74.217395   1.0   
H_L3_mean              100000.0    237.993219    158.371070  60.0   

                                25%           50%           75%           max  
MI_dir_L5_weight         100.005222    124.142029    152.947090    338.043241  
MI_dir_L5_mean            70.821446    229.649609    391.755556    566.000000  
MI_dir_L5_variance         1.623420  22579.539691  55140.127720  64008.999843  
MI_dir_L3_weight         164.674379    203.104014    238.126280    468.771918  
MI_dir_L3_mean            70.223718    279.060764    384.439978    566.000000  
MI_dir_L3_variance         2.135422  37225.662399  58075.556670  64008.999459  
MI_dir_L1_weight         491.135929    625.559423    667.079561    976.828778  
MI_dir_L1_mean            69.680411    335.989117    379.436865    566.000000  
MI_dir_L1_variance        34.036743  50817.969014  57776.319136  63674.303121  
MI_dir_L0.1_weight      4973.590777   6328.632655   6436.319494   7964.172032  
MI_dir_L0.1_mean          69.430339    336.450812    383.998941    566.000000  
MI_dir_L0.1_variance      43.488494  54821.052523  55940.399539  60490.007859  
MI_dir_L0.01_weight    21052.899069  35079.029976  50743.582018  62780.903808  
MI_dir_L0.01_mean         69.386547    336.493806    383.266392    566.000000  
MI_dir_L0.01_variance     43.516681  55134.844672  55492.325295  60311.014715  
H_L5_weight              100.005222    124.142029    152.947090    338.043241  
H_L5_mean                 70.821446    229.649609    391.755556    566.000000  
H_L5_variance              1.623420  22579.539691  55140.127720  64008.999843  
H_L3_weight              164.674379    203.104014    238.126280    468.771918  
H_L3_mean                 70.223718    279.060764    384.439978    566.000000

In [ ]:
for name, df in [("Danmini", df_dan)]:
    print(f"--- {name} class distribution ---")
    if 'label' in df.columns:
        counts = df['label'].value_counts(dropna=False)
        pct = df['label'].value_counts(normalize=True) * 100
        print(pd.concat([counts, pct.rename('percent')], axis=1))
    else:
        print("No 'label' column found. Show unique columns instead:", df.columns.tolist())
    print()

--- Danmini class distribution ---
        count  percent
label                 
mirai   85862   85.862
gafgyt   7664    7.664
benign   6474    6.474



In [ ]:
for name, df in [("Danmini", df_dan)]:
    nonnum = df.select_dtypes(exclude=['number']).columns.tolist()
    print(f"{name} non-numeric columns: {nonnum}")

Danmini non-numeric columns: ['label']


In [ ]:
#I will use Random Forest and Naive Bayes GaussianNB as the baseline ML's

In [ ]:
#The Random Forest baseline ML Implementation :

In [ ]:
import time

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier


In [ ]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    precision_recall_curve,
    auc
)

In [ ]:
#dataFrame to dataFrame 3 will be for the Danmini doorbell

In [ ]:
dataFrame = pd.read_csv("/content/Danmini/combined_danmini.csv")

In [ ]:
print("Dataset shape:", dataFrame.shape)
print(dataFrame.head())

Dataset shape: (100000, 116)
   MI_dir_L5_weight  MI_dir_L5_mean  MI_dir_L5_variance  MI_dir_L3_weight  \
0         56.956159       60.000008        1.200415e-04         74.515875   
1          3.999746      102.000000        5.460000e-12          3.999847   
2        102.247164      482.920804        3.006087e+04        179.063254   
3        152.304884      351.024155        5.907087e+04        247.726595   
4        127.088053       68.626537        4.639779e+01        205.765158   

   MI_dir_L3_mean  MI_dir_L3_variance  MI_dir_L1_weight  MI_dir_L1_mean  \
0       60.000392        5.882340e-03        209.140965       60.009242   
1      102.000000        1.820000e-12          3.999961      101.999988   
2      462.811648        3.673173e+04        597.930404      415.750605   
3      353.178703        5.887653e+04        686.987256      370.879462   
4       69.438076        4.309579e+01        640.200338       69.629745   

   MI_dir_L1_variance  MI_dir_L0.1_weight  ...  HpHp_L0.1

In [ ]:
X = dataFrame.drop(columns=["label"])
y = dataFrame["label"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

In [ ]:
#I decided to scale to make it more fair for the large numeric ranges

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
#The training of Random Forest

In [ ]:
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

In [ ]:
#The time for it more specifically

In [ ]:
start_train = time.time()
rf.fit(X_train_scaled, y_train)
end_train = time.time()


print(f"\nTraining time: {end_train - start_train:.3f} seconds")




Training time: 72.105 seconds


In [ ]:
#Interference latency measuring :

In [ ]:
start_pred = time.time()
y_pred = rf.predict(X_test_scaled)
end_pred = time.time()

latency = (end_pred - start_pred) / len(X_test)
print(f"Inference latency: {latency*1000:.6f} ms per sample")


Inference latency: 0.008758 ms per sample


In [ ]:
#Classification

In [ ]:
#f1 score is here

In [ ]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

      benign       1.00      1.00      1.00      1942
      gafgyt       1.00      1.00      1.00      2299
       mirai       1.00      1.00      1.00     25759

    accuracy                           1.00     30000
   macro avg       1.00      1.00      1.00     30000
weighted avg       1.00      1.00      1.00     30000



In [ ]:
#Confusion Matrix

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[ 1941     0     1]
 [    0  2298     1]
 [    0     0 25759]]


In [ ]:
#ROC-AUC

In [ ]:
y_proba = rf.predict_proba(X_test_scaled)

roc_auc = roc_auc_score(
    y_test,
    y_proba,
    multi_class="ovr",
    average="macro"
)

print(f"\nMacro ROC-AUC: {roc_auc:.4f}")


Macro ROC-AUC: 1.0000


In [ ]:
#PR-AUC

In [ ]:
labels = sorted(y.unique())
y_test_bin = pd.get_dummies(y_test)[labels]
pr_aucs = []

for i, cls in enumerate(labels):
    precision, recall, _ = precision_recall_curve(y_test_bin.iloc[:, i], y_proba[:, i])
    pr_auc = auc(recall, precision)
    pr_aucs.append(pr_auc)

macro_pr_auc = np.mean(pr_aucs)
print(f"Macro PR-AUC: {macro_pr_auc:.4f}")

Macro PR-AUC: 1.0000


In [ ]:
#Naive Bay Gaussian ML for Danmini doorbell:

In [ ]:
from sklearn.naive_bayes import GaussianNB


In [ ]:
from sklearn.metrics import roc_auc_score, average_precision_score, f1_score


In [ ]:
dataFrame2 = pd.read_csv("/content/Danmini/combined_danmini.csv")


In [ ]:
X = dataFrame2.drop(columns="label", axis=1)
y = dataFrame2["label"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
model_nb = GaussianNB()


In [ ]:
start_time = time.time()
model_nb.fit(X_train, y_train)
train_time = time.time() - start_time


In [ ]:
y_pred = model_nb.predict(X_test)
y_scores = model_nb.predict_proba(X_test)

In [ ]:
print("predict_proba shape:", y_scores.shape)


predict_proba shape: (20000, 3)


In [ ]:
#The metrics used :

In [ ]:
print("y_scores shape:", y_scores.shape)
print("First 5 y_scores:", y_scores[:5])

y_scores shape: (20000, 3)
First 5 y_scores: [[6.51671612e-10 9.99937904e-01 6.20954680e-05]
 [6.51117782e-10 9.99937996e-01 6.20028510e-05]
 [6.51671612e-10 9.99937904e-01 6.20954680e-05]
 [6.51671612e-10 9.99937904e-01 6.20954680e-05]
 [6.51613273e-10 9.99937911e-01 6.20881008e-05]]


In [ ]:
print(y_test.value_counts())


label
mirai     17172
gafgyt     1533
benign     1295
Name: count, dtype: int64


In [ ]:
print("Unique classes in y_train:", np.unique(y_train))


Unique classes in y_train: ['benign' 'gafgyt' 'mirai']


In [ ]:
roc_auc = roc_auc_score(y_test, y_scores, multi_class="ovr")


In [ ]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
y_test_bin = lb.fit_transform(y_test)

In [ ]:
pr_auc = average_precision_score(y_test_bin, y_scores, average="macro")


In [ ]:
f1 = f1_score(y_test, y_pred, average="macro")


In [ ]:
print(y_scores.shape)
print(np.unique(y_train))

(20000, 3)
['benign' 'gafgyt' 'mirai']


In [ ]:
start = time.time()
y_proba = model_nb.predict_proba(X_test)
end = time.time()

In [ ]:
inference_time = end - start


In [ ]:
per_sample_latency = inference_time / len(X_test)

In [ ]:
print("Gaussian Naive Bayes results for Danmini")
print(f"ROC-AUC:        {roc_auc:.4f}")
print(f"PR-AUC:         {pr_auc:.4f}")
print(f"F1 Score:       {f1:.4f}")
print(f"Train Time:     {train_time:.6f} seconds")
print(f"Inference Time (total): {inference_time:.6f} seconds")
print(f"Inference Latency (per sample): {per_sample_latency*1000:.6f} ms")


Gaussian Naive Bayes results for Danmini
ROC-AUC:        0.7004
PR-AUC:         0.4454
F1 Score:       0.0560
Train Time:     0.359936 seconds
Inference Time (total): 0.046168 seconds
Inference Latency (per sample): 0.002308 ms


In [ ]:
#Proposed model : Dense Neural Network (MLP) [This is the deep learning model] for Danmini

In [ ]:
dataFrame3 = pd.read_csv("/content/Danmini/combined_danmini.csv")


In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
#I reused the previous importing lines for ROC - AUC, PR-AUC, and f1 score

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [ ]:
X = dataFrame3.drop(columns="label", axis=1)
y = dataFrame3["label"]

In [ ]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)
num_classes = len(np.unique(y_encoded))
y_onehot = np.eye(num_classes)[y_encoded]

In [ ]:
#Scaling

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
#MLP Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_onehot, test_size=0.2, random_state=42, stratify=y_onehot
)

In [ ]:
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(num_classes, activation='softmax')
])


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
#MLP training

In [ ]:
#I made it so the max is 50 rounds (epochs)

In [ ]:
early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)
start_train = time.time()
history = model.fit(
    X_train, y_train,
    validation_split=0.1,
    epochs=50,
    batch_size=128,
    callbacks=[early_stop],
    verbose=2
)
train_time = time.time() - start_train

Epoch 1/50
563/563 - 4s - 8ms/step - accuracy: 0.9847 - loss: 0.0516 - val_accuracy: 0.9996 - val_loss: 0.0096
Epoch 2/50
563/563 - 3s - 5ms/step - accuracy: 0.9992 - loss: 0.0070 - val_accuracy: 0.9994 - val_loss: 0.0049
Epoch 3/50
563/563 - 4s - 7ms/step - accuracy: 0.9994 - loss: 0.0128 - val_accuracy: 0.9996 - val_loss: 0.0012
Epoch 4/50
563/563 - 3s - 4ms/step - accuracy: 0.9996 - loss: 0.0054 - val_accuracy: 0.9996 - val_loss: 0.0011
Epoch 5/50
563/563 - 3s - 5ms/step - accuracy: 0.9996 - loss: 0.0045 - val_accuracy: 0.9996 - val_loss: 0.0014
Epoch 6/50
563/563 - 3s - 5ms/step - accuracy: 0.9997 - loss: 0.0034 - val_accuracy: 0.9995 - val_loss: 0.0014
Epoch 7/50
563/563 - 3s - 5ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 0.9996 - val_loss: 0.0014
Epoch 8/50
563/563 - 4s - 7ms/step - accuracy: 0.9998 - loss: 9.3261e-04 - val_accuracy: 0.9996 - val_loss: 9.9504e-04
Epoch 9/50
563/563 - 3s - 5ms/step - accuracy: 0.9998 - loss: 0.0012 - val_accuracy: 0.9998 - val_loss: 

In [ ]:
start_infer = time.time()
y_pred_probs = model.predict(X_test)
inference_time = time.time() - start_infer
y_pred_classes = np.argmax(y_pred_probs, axis=1)
y_test_classes = np.argmax(y_test, axis=1)

625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [ ]:
#ROC - AUC

In [ ]:
roc_auc = roc_auc_score(y_test, y_pred_probs, multi_class="ovr")

In [ ]:
#PR - AUC

In [ ]:
pr_auc = average_precision_score(y_test, y_pred_probs)

In [ ]:
#F1

In [ ]:
f1 = f1_score(y_test_classes, y_pred_classes, average='weighted')

In [ ]:
#Latency measuring

In [ ]:
latency_per_sample_ms = (inference_time / X_test.shape[0]) * 1000


In [ ]:
print("MLP Dense Neural Network for Danmini")
print(f"ROC-AUC:        {roc_auc:.4f}")
print(f"PR-AUC:         {pr_auc:.4f}")
print(f"F1 Score:       {f1:.4f}")
print(f"Train Time:     {train_time:.4f} seconds")
print(f"Inference Time (total): {inference_time:.4f} seconds")
print(f"Inference Latency (per sample): {latency_per_sample_ms:.6f} ms")

MLP Dense Neural Network for Danmini
ROC-AUC:        1.0000
PR-AUC:         1.0000
F1 Score:       1.0000
Train Time:     83.8709 seconds
Inference Time (total): 1.7836 seconds
Inference Latency (per sample): 0.089181 ms


In [ ]:
#Provision PT 737E device section

In [ ]:
zip_path2 = "/content/combined_ProvisionPT737E.zip"

In [ ]:
extract_path2 = "/content/Provision"

In [ ]:
if not Path(extract_path2).exists():
    with zipfile.ZipFile(zip_path2, 'r') as zip_ref:
        zip_ref.extractall(extract_path2)
    print("Dataset unzipped.")
else:
    print("Dataset already unzipped.")

Dataset unzipped.


In [ ]:
#dataFrame4 to dataFrame6 will be for Provision PT737E

In [ ]:
dataFrame4 = pd.read_csv("/content/Provision/combined_ProvisionPT737E.csv")

In [ ]:
dataFrame4.head()


MI_dir_L5_weight  MI_dir_L5_mean  MI_dir_L5_variance  MI_dir_L3_weight  \
0        112.062741       74.057551            1.377905        208.657738   
1         48.679788       72.674586           16.789967         92.335144   
2         87.108279       60.181128            2.862318        105.343759   
3        124.920743      321.803060        63929.571977        179.032962   
4        160.915367       74.093378            2.232361        263.985290   

   MI_dir_L3_mean  MI_dir_L3_variance  MI_dir_L1_weight  MI_dir_L1_mean  \
0       74.058312            1.396093        739.087568       74.049114   
1       71.301255           30.474368        336.954188       69.075758   
2       60.156857            2.465921        210.408563       60.119824   
3      308.262883        63978.015914        432.709889      321.914810   
4       74.076431            1.829734        788.112718       74.059721   

   MI_dir_L1_variance  MI_dir_L0.1_weight  ...  HpHp_L0.1_covariance  \
0            1.355568         7515.962104  ...                   0.0   
1           44.703598         3755.755837  ...                   0.0   
2            1.837790         1894.974990  ...                   0.0   
3        63904.847860         2929.070847  ...                   0.0   
4            3.077971         7881.701409  ...                   0.0   

   HpHp_L0.1_pcc  HpHp_L0.01_weight  HpHp_L0.01_mean  HpHp_L0.01_std  \
0            0.0           1.000000             74.0             0.0   
1            0.0          11.638312             60.0             0.0   
2            0.0           1.000000             60.0             0.0   
3            0.0           1.000000            566.0             0.0   
4            0.0           1.687223             74.0             0.0   

   HpHp_L0.01_magnitude  HpHp_L0.01_radius  HpHp_L0.01_covariance  \
0             74.000000                0.0                    0.0   
1             60.000000                0.0                    0.0   
2             60.000000                0.0                    0.0   
3            566.000000                0.0                    0.0   
4             95.268043                0.0                    0.0   

   HpHp_L0.01_pcc   label  
0             0.0  gafgyt  
1             0.0   mirai  
2             0.0   mirai  
3             0.0   mirai  
4             0.0  gafgyt  

[5 rows x 116 columns]

In [ ]:
df_prov = pd.read_csv(zip_path2)

print("Loaded Provision:", df_prov.shape)


Loaded Provision: (100000, 116)


In [ ]:
print(" Provision head ")
display(df_prov.head())

print("\n Provision columns (count {}) ".format(len(df_prov.columns)))
print(df_prov.columns.tolist())

 Provision head 


MI_dir_L5_weight  MI_dir_L5_mean  MI_dir_L5_variance  MI_dir_L3_weight  \
0        112.062741       74.057551            1.377905        208.657738   
1         48.679788       72.674586           16.789967         92.335144   
2         87.108279       60.181128            2.862318        105.343759   
3        124.920743      321.803060        63929.571977        179.032962   
4        160.915367       74.093378            2.232361        263.985290   

   MI_dir_L3_mean  MI_dir_L3_variance  MI_dir_L1_weight  MI_dir_L1_mean  \
0       74.058312            1.396093        739.087568       74.049114   
1       71.301255           30.474368        336.954188       69.075758   
2       60.156857            2.465921        210.408563       60.119824   
3      308.262883        63978.015914        432.709889      321.914810   
4       74.076431            1.829734        788.112718       74.059721   

   MI_dir_L1_variance  MI_dir_L0.1_weight  ...  HpHp_L0.1_covariance  \
0            1.355568         7515.962104  ...                   0.0   
1           44.703598         3755.755837  ...                   0.0   
2            1.837790         1894.974990  ...                   0.0   
3        63904.847860         2929.070847  ...                   0.0   
4            3.077971         7881.701409  ...                   0.0   

   HpHp_L0.1_pcc  HpHp_L0.01_weight  HpHp_L0.01_mean  HpHp_L0.01_std  \
0            0.0           1.000000             74.0             0.0   
1            0.0          11.638312             60.0             0.0   
2            0.0           1.000000             60.0             0.0   
3            0.0           1.000000            566.0             0.0   
4            0.0           1.687223             74.0             0.0   

   HpHp_L0.01_magnitude  HpHp_L0.01_radius  HpHp_L0.01_covariance  \
0             74.000000                0.0                    0.0   
1             60.000000                0.0                    0.0   
2             60.000000                0.0                    0.0   
3            566.000000                0.0                    0.0   
4             95.268043                0.0                    0.0   

   HpHp_L0.01_pcc   label  
0             0.0  gafgyt  
1             0.0   mirai  
2             0.0   mirai  
3             0.0   mirai  
4             0.0  gafgyt  

[5 rows x 116 columns]


 Provision columns (count 116) 
['MI_dir_L5_weight', 'MI_dir_L5_mean', 'MI_dir_L5_variance', 'MI_dir_L3_weight', 'MI_dir_L3_mean', 'MI_dir_L3_variance', 'MI_dir_L1_weight', 'MI_dir_L1_mean', 'MI_dir_L1_variance', 'MI_dir_L0.1_weight', 'MI_dir_L0.1_mean', 'MI_dir_L0.1_variance', 'MI_dir_L0.01_weight', 'MI_dir_L0.01_mean', 'MI_dir_L0.01_variance', 'H_L5_weight', 'H_L5_mean', 'H_L5_variance', 'H_L3_weight', 'H_L3_mean', 'H_L3_variance', 'H_L1_weight', 'H_L1_mean', 'H_L1_variance', 'H_L0.1_weight', 'H_L0.1_mean', 'H_L0.1_variance', 'H_L0.01_weight', 'H_L0.01_mean', 'H_L0.01_variance', 'HH_L5_weight', 'HH_L5_mean', 'HH_L5_std', 'HH_L5_magnitude', 'HH_L5_radius', 'HH_L5_covariance', 'HH_L5_pcc', 'HH_L3_weight', 'HH_L3_mean', 'HH_L3_std', 'HH_L3_magnitude', 'HH_L3_radius', 'HH_L3_covariance', 'HH_L3_pcc', 'HH_L1_weight', 'HH_L1_mean', 'HH_L1_std', 'HH_L1_magnitude', 'HH_L1_radius', 'HH_L1_covariance', 'HH_L1_pcc', 'HH_L0.1_weight', 'HH_L0.1_mean', 'HH_L0.1_std', 'HH_L0.1_magnitude', 'HH_L0.1

In [ ]:
print("\n\n Provision info ")
df_prov.info()



 Provision info 
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Columns: 116 entries, MI_dir_L5_weight to label
dtypes: float64(115), object(1)
memory usage: 88.5+ MB


In [ ]:
for name, df in [("Provision", df_prov)]:
    print(f"--- {name} class distribution ---")
    if 'label' in df.columns:
        counts = df['label'].value_counts(dropna=False)
        pct = df['label'].value_counts(normalize=True) * 100
        print(pd.concat([counts, pct.rename('percent')], axis=1))
    else:
        print("No 'label' column found. Show unique columns instead:", df.columns.tolist())
    print()

--- Provision class distribution ---
        count  percent
label                 
mirai   77981   77.981
gafgyt  11043   11.043
benign  10976   10.976



In [ ]:
for name, df in [("Provision", df_prov)]:
    nonnum = df.select_dtypes(exclude=['number']).columns.tolist()
    print(f"{name} non-numeric columns: {nonnum}")

Provision non-numeric columns: ['label']


In [ ]:
#Random forest implementation for Provision

In [ ]:
X = dataFrame4.drop(columns="label", axis=1)
y = dataFrame4["label"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
#The scaling

In [ ]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
#The training and time taken for training

In [ ]:
rf2 = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

start_train = time.time()
rf2.fit(X_train_scaled, y_train)
end_train = time.time()


print(f"\nTraining time: {end_train - start_train:.3f} seconds")


Training time: 59.827 seconds


In [ ]:
start_pred = time.time()
y_pred = rf2.predict(X_test_scaled)
end_pred = time.time()

latency = (end_pred - start_pred) / len(X_test)
print(f"Inference latency: {latency*1000:.6f} ms per sample")

Inference latency: 0.009081 ms per sample


In [ ]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

      benign       1.00      1.00      1.00      2195
      gafgyt       1.00      1.00      1.00      2209
       mirai       1.00      1.00      1.00     15596

    accuracy                           1.00     20000
   macro avg       1.00      1.00      1.00     20000
weighted avg       1.00      1.00      1.00     20000



In [ ]:
#Confusion Matrix

In [ ]:
print(confusion_matrix(y_test, y_pred))

[[ 2195     0     0]
 [    0  2209     0]
 [    0     0 15596]]


In [ ]:
#ROC-AUC

In [ ]:
y_proba = rf2.predict_proba(X_test_scaled)

roc_auc = roc_auc_score(
    y_test,
    y_proba,
    multi_class="ovr",
    average="macro"
)

In [ ]:
#PR - AUC

In [ ]:
labels = sorted(y.unique())
y_test_bin = pd.get_dummies(y_test)[labels]
pr_aucs = []

for i, cls in enumerate(labels):
    precision, recall, _ = precision_recall_curve(y_test_bin.iloc[:, i], y_proba[:, i])
    pr_auc = auc(recall, precision)
    pr_aucs.append(pr_auc)

macro_pr_auc = np.mean(pr_aucs)


In [ ]:
#f1

In [ ]:
f1_second = f1_score(y_test, y_pred, average='weighted')


In [ ]:
#Results for Random Forest training in Provision dataset

print(f"\nMacro ROC-AUC:   {roc_auc:.4f}")
print(f"Macro PR-AUC:    {macro_pr_auc:.4f}")
print(f"F1 Score:        {f1_second:.4f}")
print(f"Inference latency: {latency*1000:.6f} ms per sample")
print(f"\nTraining time: {end_train - start_train:.3f} seconds")


Macro ROC-AUC:   1.0000
Macro PR-AUC:    1.0000
F1 Score:        1.0000
Inference latency: 0.009081 ms per sample

Training time: 59.827 seconds


In [ ]:
#Naive Bay GaussianNB ML implemenatation :

In [ ]:
dataFrame5 = pd.read_csv("/content/Provision/combined_ProvisionPT737E.csv")


In [ ]:
X = dataFrame5.drop(columns="label", axis=1)
y = dataFrame5["label"]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
model_nb2 = GaussianNB()

In [ ]:
start_time = time.time()
model_nb2.fit(X_train, y_train)
train_time = time.time() - start_time

In [ ]:
y_pred = model_nb2.predict(X_test)
y_scores = model_nb2.predict_proba(X_test)

In [ ]:
print("predict_proba shape:", y_scores.shape)

predict_proba shape: (20000, 3)


In [ ]:
print("y_scores shape:", y_scores.shape)
print("First 5 y_scores:", y_scores[:5])

y_scores shape: (20000, 3)
First 5 y_scores: [[2.76279224e-12 9.99999627e-01 3.73316476e-07]
 [2.76279224e-12 9.99999627e-01 3.73316476e-07]
 [2.76202533e-12 9.99999627e-01 3.73238692e-07]
 [2.76279107e-12 9.99999627e-01 3.73304809e-07]
 [2.76239722e-12 9.99999627e-01 3.73272347e-07]]


In [ ]:
print(y_test.value_counts())

label
mirai     15596
gafgyt     2209
benign     2195
Name: count, dtype: int64


In [ ]:
print("Unique classes in y_train:", np.unique(y_train))

Unique classes in y_train: ['benign' 'gafgyt' 'mirai']


In [ ]:
roc_auc = roc_auc_score(y_test, y_scores, multi_class="ovr")


In [ ]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
y_test_bin = lb.fit_transform(y_test)

In [ ]:
pr_auc = average_precision_score(y_test_bin, y_scores, average="macro")

In [ ]:
f1_second = f1_score(y_test, y_pred, average="macro")

In [ ]:
print(y_scores.shape)
print(np.unique(y_train))

(20000, 3)
['benign' 'gafgyt' 'mirai']


In [ ]:
start = time.time()
y_proba = model_nb2.predict_proba(X_test)
end = time.time()

In [ ]:
inference_time = end - start

In [ ]:
per_sample_latency = inference_time / len(X_test)

In [ ]:
print("Gaussian Naive Bayes results for Provision")
print(f"ROC-AUC:        {roc_auc:.4f}")
print(f"PR-AUC:         {pr_auc:.4f}")
print(f"F1 Score:       {f1_second:.4f}")
print(f"Train Time:     {train_time:.6f} seconds")
print(f"Inference Time (total): {inference_time:.6f} seconds")
print(f"Inference Latency (per sample): {per_sample_latency*1000:.6f} ms")


Gaussian Naive Bayes results for Provision
ROC-AUC:        0.6712
PR-AUC:         0.4426
F1 Score:       0.0772
Train Time:     0.289524 seconds
Inference Time (total): 0.040955 seconds
Inference Latency (per sample): 0.002048 ms


In [ ]:
#Proposed model : Dense Neural Network (MLP) [This is the deep learning model] for Provision

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [ ]:
dataFrame6 = pd.read_csv("/content/Provision/combined_ProvisionPT737E.csv")

In [ ]:
X = dataFrame6.drop(columns="label", axis=1)
y = dataFrame6["label"]

In [ ]:
le = LabelEncoder()
y_encoded = le.fit_transform(y)
num_classes = len(np.unique(y_encoded))
y_onehot = np.eye(num_classes)[y_encoded]

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_onehot, test_size=0.2, random_state=42, stratify=y_onehot
)

In [ ]:
model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(num_classes, activation='softmax')
])


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
#MLP training :

In [ ]:
early_stop = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=20, restore_best_weights=True)
start_train = time.time()
history = model.fit(
    X_train, y_train,
    validation_split=0.1,
    epochs=50,
    batch_size=128,
    callbacks=[early_stop],
    verbose=2
)
train_time = time.time() - start_train

Epoch 1/50
563/563 - 9s - 16ms/step - accuracy: 0.9998 - loss: 0.0013 - val_accuracy: 1.0000 - val_loss: 1.1851e-04
Epoch 2/50
563/563 - 5s - 9ms/step - accuracy: 0.9999 - loss: 3.1036e-04 - val_accuracy: 1.0000 - val_loss: 1.3574e-04
Epoch 3/50
563/563 - 7s - 13ms/step - accuracy: 0.9999 - loss: 5.6669e-04 - val_accuracy: 1.0000 - val_loss: 7.7325e-05
Epoch 4/50
563/563 - 2s - 4ms/step - accuracy: 0.9999 - loss: 2.6843e-04 - val_accuracy: 1.0000 - val_loss: 4.0536e-05
Epoch 5/50
563/563 - 3s - 4ms/step - accuracy: 0.9999 - loss: 8.8920e-04 - val_accuracy: 0.9992 - val_loss: 0.0022
Epoch 6/50
563/563 - 2s - 4ms/step - accuracy: 0.9998 - loss: 6.9042e-04 - val_accuracy: 1.0000 - val_loss: 5.7990e-05
Epoch 7/50
563/563 - 4s - 6ms/step - accuracy: 0.9998 - loss: 5.8259e-04 - val_accuracy: 1.0000 - val_loss: 4.9318e-05
Epoch 8/50
563/563 - 2s - 4ms/step - accuracy: 0.9999 - loss: 4.9113e-04 - val_accuracy: 1.0000 - val_loss: 1.3243e-04
Epoch 9/50
563/563 - 2s - 4ms/step - accuracy: 0.9999 

In [ ]:
start_infer = time.time()
y_pred_probs = model.predict(X_test)
inference_time = time.time() - start_infer
y_pred_classes = np.argmax(y_pred_probs, axis=1)
y_test_classes = np.argmax(y_test, axis=1)

625/625 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step


In [ ]:
#ROC - AUC

In [ ]:
roc_auc = roc_auc_score(y_test, y_pred_probs, multi_class="ovr")

In [ ]:
#PR - AUC

In [ ]:
pr_auc = average_precision_score(y_test, y_pred_probs)

In [ ]:
#F1

In [ ]:
f1_second = f1_score(y_test_classes, y_pred_classes, average='weighted')

In [ ]:
#Latency measuring

In [ ]:
latency_per_sample_ms = (inference_time / X_test.shape[0]) * 1000


In [ ]:
print("MLP Dense Neural Network for Provision")
print(f"ROC-AUC:        {roc_auc:.4f}")
print(f"PR-AUC:         {pr_auc:.4f}")
print(f"F1 Score:       {f1_second:.4f}")
print(f"Train Time:     {train_time:.4f} seconds")
print(f"Inference Time (total): {inference_time:.4f} seconds")
print(f"Inference Latency (per sample): {latency_per_sample_ms:.6f} ms")

MLP Dense Neural Network for Provision
ROC-AUC:        1.0000
PR-AUC:         1.0000
F1 Score:       0.9999
Train Time:     97.6932 seconds
Inference Time (total): 1.0956 seconds
Inference Latency (per sample): 0.054778 ms
